/*try {
    const result = 10;
    result = 0;
    console.log(result);
} catch (error) {
        console.log("Nuestro error: " + error.message);
}

const saludar = () => {console.log("Hola")}





*/

var sumar2 = (x, y) => {return x + y};

console.log(sumar2(5, 8));



